import { FormEvent, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { ArrowLeft, LockKeyhole, Mic2, Radio, ShieldCheck, TicketCheck, UserCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { apiErrorMessage } from '@/api/client';
import { hostingApi } from '@/features/hosting/hosting.api';

export function CreateRoomPage(){
  const navigate=useNavigate();
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [category,setCategory]=useState('Audio Lounge'); const [language,setLanguage]=useState('en');
  const [inviteOnly,setInviteOnly]=useState(false); const [locked,setLocked]=useState(false); const [subscriberOnly,setSubscriberOnly]=useState(false); const [verifiedOnly,setVerifiedOnly]=useState(false); const [ticketed,setTicketed]=useState(false); const [price,setPrice]=useState('0'); const [error,setError]=useState('');
  const create=useMutation({mutationFn:()=>hostingApi.createRoom({title:title.trim(),description:description.trim()||undefined,category,language,isPrivate:inviteOnly,isInviteOnly:inviteOnly,isLocked:locked,isSubscriberOnly:subscriberOnly,isVerifiedOnly:verifiedOnly,isPremium:ticketed,isTicketRequired:ticketed,ticketPriceAmount:ticketed?Number(price||0):0}),onSuccess:r=>navigate(`/host/rooms/${r.id}/settings`,{replace:true}),onError:e=>setError(apiErrorMessage(e))});
  function submit(e:FormEvent){e.preventDefault();setError('');if(!title.trim()){setError('Room title is required.');return}create.mutate()}
  return <div className="vc-page-width vc-ph06-page"><button className="vc-room-back" onClick={()=>navigate('/host/rooms')}><ArrowLeft/>My Rooms</button><section className="vc-ph06-form-shell"><div className="vc-ph06-form-intro"><span className="vc-eyebrow"><Mic2/>Create room</span><h1>Build your next <em>live room.</em></h1><p>The backend remains authoritative for Host approval, lifecycle and restricted-room access.</p></div><form className="vc-ph06-form" onSubmit={submit}><label>Room title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give your room a clear title"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="What will you talk about?"/></label><div className="vc-ph06-form-grid"><label>Category<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="hi">Hindi</option><option value="ta">Tamil</option><option value="ml">Malayalam</option><option value="ar">Arabic</option></select></label></div><fieldset><legend>Access & privacy</legend><label className="vc-ph06-toggle"><input type="checkbox" checked={inviteOnly} onChange={e=>setInviteOnly(e.target.checked)}/><span><LockKeyhole/><b>Invite only</b><small>Only users invited by the host can enter.</small></span></label><label className="vc-ph06-toggle"><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/><span><ShieldCheck/><b>Locked room</b><small>Require explicit room-level access.</small></span></label><label className="vc-ph06-toggle"><input type="checkbox" checked={subscriberOnly} onChange={e=>setSubscriberOnly(e.target.checked)}/><span><UserCheck/><b>Subscribers only</b><small>Restrict entry to eligible subscribers.</small></span></label><label className="vc-ph06-toggle"><input type="checkbox" checked={verifiedOnly} onChange={e=>setVerifiedOnly(e.target.checked)}/><span><UserCheck/><b>Verified users only</b><small>Require a verified VoiceCloud identity.</small></span></label><label className="vc-ph06-toggle"><input type="checkbox" checked={ticketed} onChange={e=>setTicketed(e.target.checked)}/><span><TicketCheck/><b>Ticketed room</b><small>Require a paid ticket before entry.</small></span></label>{ticketed?<label>Ticket price (USD)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label>:null}</fieldset>{error?<div className="vc-ph06-alert">{error}</div>:null}<div className="vc-ph06-form-actions"><button type="button" className="vc-button vc-button--secondary" onClick={()=>navigate('/host/rooms')}>Cancel</button><button className="vc-button vc-button--primary" disabled={create.isPending}><Radio/>{create.isPending?'Creating…':'Create Room'}</button></div></form></section></div>
}
