import { useMutation, useQuery } from '@tanstack/react-query';
import { BellRing, CalendarDays, Clock3, Radio, Users } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { apiErrorMessage } from '@/api/client';
import { useWebsiteAuthStore } from '@/auth/auth.store';
import { DiscoveryError, DiscoveryLoading } from '@/components/discovery/DiscoveryStates';
import { eventsApi } from '@/features/community/community.api';

export function EventDetailsPage(){const {eventId=''}=useParams();const navigate=useNavigate();const auth=useWebsiteAuthStore(s=>s.isAuthenticated);const event=useQuery({queryKey:['ph04','event',eventId],queryFn:()=>eventsApi.detail(eventId),enabled:Boolean(eventId)});const reminder=useMutation({mutationFn:()=>eventsApi.reminder(eventId)});if(event.isPending)return <div className="vc-page-width vc-ph04-page"><DiscoveryLoading/></div>;if(event.isError||!event.data)return <div className="vc-page-width vc-ph04-page"><DiscoveryError error={event.error}/></div>;const item=event.data;return <div className="vc-page-width vc-ph04-page"><section className="vc-event-detail"><div className="vc-event-detail__art" style={item.coverUrl?{backgroundImage:`url(${item.coverUrl})`}:undefined}><span className="vc-eyebrow"><Radio size={14}/>{item.status}</span></div><div className="vc-event-detail__copy"><span className="vc-eyebrow">{item.category} · {item.language}</span><h1>{item.title}</h1><p>{item.description || 'A scheduled VoiceCloud conversation.'}</p><div className="vc-event-detail__facts"><span><CalendarDays/>{new Date(item.scheduledStartTime).toLocaleDateString()}</span><span><Clock3/>{new Date(item.scheduledStartTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · {item.durationMinutes} min</span><span><Users/>{item.rsvpCount ?? 0} interested</span></div>{reminder.isError?<div className="vc-inline-error">{apiErrorMessage(reminder.error)}</div>:null}{reminder.isSuccess?<div className="vc-inline-success">Reminder registered. Current RSVP count: {reminder.data.rsvpCount}</div>:null}<button className="vc-button vc-button--primary" disabled={reminder.isPending||reminder.isSuccess} onClick={()=>auth?reminder.mutate():navigate('/auth/sign-in')}><BellRing size={17}/> {auth?'Set reminder':'Sign in to set reminder'}</button>{item.club?.handle?<button className="vc-button vc-button--secondary" onClick={()=>navigate(`/communities/${item.club!.handle}`)}>View community</button>:null}</div></section></div>}
