import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarClock, Clock3, Edit3, Pause, Play, Plus, Radio, Square, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { apiErrorMessage } from '@/api/client';
import { DiscoveryError, DiscoveryLoading } from '@/components/discovery/DiscoveryStates';
import { hostingApi } from '@/features/hosting/hosting.api';
import { useWebsiteAuthStore } from '@/auth/auth.store';
import type { ScheduledRoom } from '@/features/hosting/types';

function splitLocal(iso?: string){if(!iso)return {date:'',time:''};const d=new Date(iso);const pad=(n:number)=>String(n).padStart(2,'0');return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}}

export function HostSchedulePage(){
 const navigate=useNavigate();const qc=useQueryClient();const user=useWebsiteAuthStore(s=>s.user);const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 const schedule=useQuery({queryKey:['ph06','schedule',user?.id],queryFn:()=>hostingApi.scheduled(user!.id),enabled:Boolean(user?.id)});const rooms=useQuery({queryKey:['ph06','my-rooms','schedule-link'],queryFn:()=>hostingApi.ownedRooms(),enabled:Boolean(user?.id)});
 const [editing,setEditing]=useState<ScheduledRoom|null>(null);const[title,setTitle]=useState('');const[date,setDate]=useState('');const[time,setTime]=useState('');const[description,setDescription]=useState('');const[inviteOnly,setInviteOnly]=useState(false);const[notice,setNotice]=useState('');const[showForm,setShowForm]=useState(false);
 const roomBySchedule=useMemo(()=>new Map((rooms.data?.data||[]).filter(r=>r.scheduledRoomId).map(r=>[r.scheduledRoomId!,r])),[rooms.data]);
 const refresh=()=>{void qc.invalidateQueries({queryKey:['ph06','schedule']});void qc.invalidateQueries({queryKey:['ph06','my-rooms']})};
 function openCreate(){setEditing(null);setTitle('');setDate('');setTime('');setDescription('');setInviteOnly(false);setShowForm(true)}
 function openEdit(item:ScheduledRoom){const local=splitLocal(item.scheduledStartTime);setEditing(item);setTitle(item.title);setDate(local.date);setTime(local.time);setDescription(item.description||'');setInviteOnly(Boolean(item.isInviteOnly));setShowForm(true)}
 const save=useMutation({mutationFn:async()=>{const local=new Date(`${date}T${time}:00`);if(Number.isNaN(local.getTime())||local.getTime()<=Date.now())throw new Error('Schedule time must be in the future.');const payload={title:title.trim(),description:description.trim()||undefined,scheduledStartTime:local.toISOString(),timeZone:tz,durationMinutes:60,visibility:inviteOnly?'PRIVATE':'PUBLIC',isInviteOnly:inviteOnly};return editing?hostingApi.updateScheduled(editing.id,payload):hostingApi.createScheduled(payload)},onSuccess:()=>{setShowForm(false);refresh();setNotice('Schedule saved in your local timezone.')},onError:e=>setNotice(apiErrorMessage(e))});
 const remove=useMutation({mutationFn:hostingApi.deleteScheduled,onSuccess:refresh,onError:e=>setNotice(apiErrorMessage(e))});
 const start=useMutation({mutationFn:async(item:ScheduledRoom)=>{let linked=roomBySchedule.get(item.id);if(!linked){linked=await hostingApi.createRoom({title:item.title,description:item.description,category:item.category||'Audio Lounge',language:item.language||'en',scheduledRoomId:item.id,isPrivate:Boolean(item.isInviteOnly),isInviteOnly:Boolean(item.isInviteOnly),isPremium:Boolean(item.isPremium),isTicketRequired:Boolean(item.isPremium),ticketPriceAmount:Number(item.ticketPriceAmount||0)})}if(String(linked.status).toLowerCase()!=='live')linked=await hostingApi.startBroadcast(linked.id);return linked},onSuccess:r=>{refresh();navigate(`/rooms/${r.id}/live`)},onError:e=>setNotice(apiErrorMessage(e))});
 const pause=useMutation({mutationFn:hostingApi.pause,onSuccess:refresh,onError:e=>setNotice(apiErrorMessage(e))});
 const resume=useMutation({mutationFn:hostingApi.resume,onSuccess:refresh,onError:e=>setNotice(apiErrorMessage(e))});
 const end=useMutation({mutationFn:hostingApi.endBroadcast,onSuccess:refresh,onError:e=>setNotice(apiErrorMessage(e))});
 return <div className="vc-page-width vc-ph06-page"><section className="vc-ph06-hero"><div><span className="vc-eyebrow"><CalendarClock/>Host scheduling</span><h1>Schedule <em>Rooms</em></h1><p>Times are entered in <strong>{tz}</strong>, stored as a UTC instant and rendered in each viewer's local timezone.</p></div><div className="vc-ph06-hero__actions"><button className="vc-button vc-button--secondary" onClick={()=>navigate('/host/rooms')}><Radio/>My Rooms</button><button className="vc-button vc-button--primary" onClick={openCreate}><Plus/>Schedule Room</button></div></section>{notice?<div className="vc-ph06-alert">{notice}<button onClick={()=>setNotice('')}>×</button></div>:null}
 {showForm?<form className="vc-ph06-inline-form" onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate()}}><div><h2>{editing?'Edit scheduled room':'Schedule a future room'}</h2><p>Local timezone: {tz}</p></div><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Description<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="vc-ph06-toggle compact"><input type="checkbox" checked={inviteOnly} onChange={e=>setInviteOnly(e.target.checked)}/><span><b>Invite only</b><small>Require a host invitation when this room goes live.</small></span></label><div className="vc-ph06-form-actions"><button type="button" className="vc-button vc-button--secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="vc-button vc-button--primary" disabled={!title.trim()||!date||!time||save.isPending}>{save.isPending?'Saving…':'Save Schedule'}</button></div></form>:null}
 {schedule.isPending?<DiscoveryLoading/>:schedule.isError?<DiscoveryError error={schedule.error}/>:schedule.data?.data.length?<section className="vc-ph06-schedule-grid">{schedule.data.data.map(item=>{const linked=roomBySchedule.get(item.id);const live=String(linked?.status||'').toLowerCase()==='live';const paused=String(linked?.status||'').toLowerCase()==='paused';const editable=['scheduled','postponed'].includes(String(item.status).toLowerCase());const d=new Date(item.scheduledStartTime);return <article key={item.id}><header><span className={live?'live':''}>{live?'LIVE':paused?'PAUSED':String(item.status).toUpperCase()}</span><small>{item.rsvpCount||0} reminders</small></header><h2>{item.title}</h2><p>{item.description||'Scheduled VoiceCloud room'}</p><div className="vc-ph06-schedule-time"><CalendarClock/>{d.toLocaleDateString(undefined,{dateStyle:'medium'})}<Clock3/>{d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',timeZoneName:'short'})}</div><div className="vc-ph06-room-card__actions">{!live&&!paused?<button className="primary" onClick={()=>start.mutate(item)} disabled={start.isPending}><Play/>{linked?'Start Linked Broadcast':'Create & Start Broadcast'}</button>:null}{live?<button onClick={()=>pause.mutate(linked!.id)} disabled={pause.isPending}><Pause/>Pause</button>:null}{paused?<button className="primary" onClick={()=>resume.mutate(linked!.id)} disabled={resume.isPending}><Play/>Resume</button>:null}{live||paused?<button onClick={()=>navigate(`/rooms/${linked!.id}/live`)}><Radio/>Open Host Room</button>:null}{live||paused?<button className="danger" onClick={()=>end.mutate(linked!.id)} disabled={end.isPending}><Square/>End</button>:null}{editable&&!live&&!paused?<button onClick={()=>openEdit(item)}><Edit3/>Edit Date & Time</button>:null}{editable&&!live&&!paused?<button className="danger ghost" onClick={()=>window.confirm('Cancel this scheduled room?')&&remove.mutate(item.id)}><Trash2/>Cancel Schedule</button>:null}</div></article>})}</section>:<section className="vc-ph06-empty"><CalendarClock/><h2>No scheduled rooms</h2><p>Plan your next broadcast using your local date and time.</p><button className="vc-button vc-button--primary" onClick={openCreate}><Plus/>Schedule Room</button></section>}
 </div>
}
