import { useQuery } from '@tanstack/react-query';
import { BadgeCheck, BookOpen, Compass, Edit3, Mic2, Share2, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { profileApi } from '@/features/discovery/discovery.api';
import { compactNumber, userAvatar } from '@/features/discovery/presentation';
import { DiscoveryError, DiscoveryLoading } from '@/components/discovery/DiscoveryStates';

export function MyProfilePage(){const navigate=useNavigate();const q=useQuery({queryKey:['ph03','profile','me'],queryFn:profileApi.me});if(q.isPending)return <DiscoveryLoading label="Loading your profile…"/>;if(q.isError)return <DiscoveryError error={q.error}/>;const p=q.data;return <div className="vc-page-width vc-profile-page vc-my-profile">
<section className="vc-profile-hero"><div className="vc-profile-hero__cover"/><div className="vc-profile-hero__content"><div className="vc-profile-avatar"><img src={userAvatar(p)} alt=""/>{p.isOnline?<i/>:null}</div><div className="vc-profile-copy"><span className="vc-profile-badge">Your VoiceCloud profile</span><h1>{p.displayName}{p.isVerified?<BadgeCheck size={28}/>:null}</h1><strong>@{p.username}</strong><p>{p.bio||p.statusMessage||'Add a bio during profile editing to tell people about yourself.'}</p><div className="vc-profile-tags">{(p.interests||[]).slice(0,5).map(t=><span key={t}>{t}</span>)}</div></div><div className="vc-my-profile__actions">{p.role==='CREATOR'?<button onClick={()=>navigate('/host/rooms')}><Mic2/>My Rooms</button>:null}<button disabled title="Profile editing is implemented in a later website phase"><Edit3/>Edit Profile</button><button onClick={()=>navigator.clipboard?.writeText(`${location.origin}/profile/${p.username}`)}><Share2/>Share Profile</button></div></div></section>
<section className="vc-profile-stats"><button onClick={()=>navigate('/followers')}><b>{compactNumber(p.stats?.followersCount??p.followersCount)}</b><span>Followers</span></button><button onClick={()=>navigate('/following')}><b>{compactNumber(p.stats?.followingCount??p.followingCount)}</b><span>Following</span></button><div><b>{p.profileCompletionPercentage??0}%</b><span>Profile complete</span></div><div><b>{p.stats?.badgesCount??0}</b><span>Badges</span></div></section>
<div className="vc-my-profile-grid"><section className="vc-profile-content"><h2>Your profile overview</h2><div className="vc-profile-levels"><div><BookOpen/><small>Interests</small><b>{p.interests?.length||0}</b></div><div><Compass/><small>Popularity</small><b>{compactNumber(p.popularityScore)}</b></div><div><Users/><small>Community reach</small><b>{compactNumber(p.stats?.followersCount??p.followersCount)}</b></div></div><h3>Interests</h3><div className="vc-profile-interest-grid">{p.interests?.length?p.interests.map(t=><span key={t}>{t}</span>):<span>No interests selected yet.</span>}</div></section><aside className="vc-profile-progress"><h3>Profile completeness</h3><div><i style={{width:`${Math.min(100,p.profileCompletionPercentage??0)}%`}}/></div><b>{p.profileCompletionPercentage??0}%</b><p>Profile data comes from the authenticated VoiceCloud profile API.</p></aside></div>
</div>}
