import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, CheckCheck, Gift, Megaphone, Radio, ShieldCheck, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { DiscoveryEmpty, DiscoveryError, DiscoveryLoading } from '@/components/discovery/DiscoveryStates';
import { notificationsApi } from '@/features/notifications/notifications.api';
import type { VoiceCloudNotification } from '@/features/notifications/types';
import { connectWebsiteSocket } from '@/realtime/socket.client';
import { useEffect } from 'react';

function notificationIcon(type:string){if(type==='GIFT')return <Gift/>;if(type==='ROOM_INVITATION')return <Radio/>;if(type==='ANNOUNCEMENT')return <Megaphone/>;if(type==='HOST_APPROVAL')return <ShieldCheck/>;return <Bell/>}
function destination(item:VoiceCloudNotification){const data=item.data||{};const conversationId=typeof data.conversationId==='string'?data.conversationId:null;const roomId=typeof data.roomId==='string'?data.roomId:null;const clubId=typeof data.clubId==='string'?data.clubId:null;if(conversationId)return `/messages/${conversationId}`;if(roomId)return `/rooms/${roomId}`;if(clubId)return `/communities/${clubId}`;return null}

export function NotificationsPage(){const navigate=useNavigate();const qc=useQueryClient();const list=useQuery({queryKey:['ph04','notifications'],queryFn:()=>notificationsApi.list()});const refresh=()=>{qc.invalidateQueries({queryKey:['ph04','notifications']});qc.invalidateQueries({queryKey:['ph04','notifications','unread']})};const read=useMutation({mutationFn:notificationsApi.markRead,onSuccess:refresh});const readAll=useMutation({mutationFn:notificationsApi.markAllRead,onSuccess:refresh});const remove=useMutation({mutationFn:notificationsApi.remove,onSuccess:refresh});useEffect(()=>{const socket=connectWebsiteSocket();const update=()=>refresh();socket.on('notification:new',update);socket.on('notification:read',update);socket.on('notification:deleted',update);return()=>{socket.off('notification:new',update);socket.off('notification:read',update);socket.off('notification:deleted',update)}},[]);return <div className="vc-page-width vc-ph04-page"><section className="vc-ph04-titlebar"><div><span className="vc-eyebrow"><Bell size={14}/> Notifications</span><h1>What’s happening around you</h1><p>Notification delivery, unread state and deletion are controlled by the authenticated notification service.</p></div><button className="vc-button vc-button--secondary" disabled={readAll.isPending} onClick={()=>readAll.mutate()}><CheckCheck size={16}/> Mark all read</button></section>{list.isPending?<DiscoveryLoading/>:list.isError?<DiscoveryError error={list.error}/>:list.data?.data.length?<section className="vc-notification-list">{list.data.data.map(item=><article key={item.id} className={`vc-notification-card${item.isRead?'':' unread'}`}><div className="vc-notification-card__icon">{notificationIcon(item.type)}</div><button type="button" className="vc-notification-card__body" onClick={()=>{if(!item.isRead)read.mutate(item.id);const target=destination(item);if(target)navigate(target)}}><strong>{item.title}</strong><p>{item.message}</p><small>{item.type.replaceAll('_',' ')} · {new Date(item.createdAt).toLocaleString()}</small></button><div className="vc-notification-card__actions">{!item.isRead?<button title="Mark read" onClick={()=>read.mutate(item.id)}><CheckCheck/></button>:null}<button title="Delete" onClick={()=>remove.mutate(item.id)}><Trash2/></button></div></article>)}</section>:<DiscoveryEmpty title="You're all caught up" description="New VoiceCloud notifications will appear here."/>}</div>}
