import { FormEvent, useEffect, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowLeft, Save, ShieldCheck } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { apiErrorMessage } from '@/api/client';
import { DiscoveryError, DiscoveryLoading } from '@/components/discovery/DiscoveryStates';
import { hostingApi } from '@/features/hosting/hosting.api';
import { roomApi } from '@/features/rooms/room.api';
import { useWebsiteAuthStore } from '@/auth/auth.store';

export function RoomSettingsPage(){const {roomId=''}=useParams();const navigate=useNavigate();const user=useWebsiteAuthStore(s=>s.user);const room=useQuery({queryKey:['ph06','room-settings',roomId],queryFn:()=>roomApi.detail(roomId),enabled:Boolean(roomId)});const [title,setTitle]=useState('');const[description,setDescription]=useState('');const[inviteOnly,setInviteOnly]=useState(false);const[locked,setLocked]=useState(false);const[subscriberOnly,setSubscriberOnly]=useState(false);const[verifiedOnly,setVerifiedOnly]=useState(false);const[ticketed,setTicketed]=useState(false);const[price,setPrice]=useState('0');const[notice,setNotice]=useState('');useEffect(()=>{if(!room.data)return;setTitle(room.data.title||'');setDescription(room.data.description||'');setInviteOnly(Boolean(room.data.isInviteOnly));setLocked(Boolean(room.data.isLocked));setSubscriberOnly(Boolean(room.data.isSubscriberOnly));setVerifiedOnly(Boolean(room.data.isVerifiedOnly));setTicketed(Boolean(room.data.isTicketRequired||room.data.isPremium));setPrice(String(room.data.ticketPriceAmount||0))},[room.data]);const save=useMutation({mutationFn:()=>hostingApi.updateRoom(roomId,{title:title.trim(),description:description.trim()||undefined,isPrivate:inviteOnly,isInviteOnly:inviteOnly,isLocked:locked,isSubscriberOnly:subscriberOnly,isVerifiedOnly:verifiedOnly,isPremium:ticketed,isTicketRequired:ticketed,ticketPriceAmount:ticketed?Number(price||0):0}),onSuccess:()=>setNotice('Room settings saved.'),onError:e=>setNotice(apiErrorMessage(e))});if(room.isPending)return <div className="vc-page-width vc-ph06-page"><DiscoveryLoading/></div>;if(room.isError||!room.data)return <div className="vc-page-width vc-ph06-page"><DiscoveryError error={room.error}/></div>;if(room.data.hostId!==user?.id)return <div className="vc-page-width vc-ph06-page"><section className="vc-ph06-access"><ShieldCheck/><h1>Host controls unavailable</h1><p>Only the room owner can change these settings.</p></section></div>;function submit(e:FormEvent){e.preventDefault();setNotice('');save.mutate()}return <div className="vc-page-width vc-ph06-page"><button className="vc-room-back" onClick={()=>navigate('/host/rooms')}><ArrowLeft/>My Rooms</button><section className="vc-ph06-form-shell"><div className="vc-ph06-form-intro"><span className="vc-eyebrow"><ShieldCheck/>Room access & privacy</span><h1>Control who can <em>enter.</em></h1><p>Changes are enforced by the backend and RTC join authority, not only by the page UI.</p></div><form className="vc-ph06-form" onSubmit={submit}><label>Room title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><fieldset><legend>Access rules</legend>{[
  { label: 'Invite only', value: inviteOnly, setValue: setInviteOnly },
  { label: 'Locked room', value: locked, setValue: setLocked },
  { label: 'Subscribers only', value: subscriberOnly, setValue: setSubscriberOnly },
  { label: 'Verified users only', value: verifiedOnly, setValue: setVerifiedOnly },
  { label: 'Ticket required', value: ticketed, setValue: setTicketed },
].map(({label,value,setValue})=><label className="vc-ph06-switch-row" key={label}><span><b>{label}</b><small>Server-authoritative room access restriction.</small></span><input type="checkbox" checked={value} onChange={e=>setValue(e.target.checked)}/></label>)}{ticketed?<label>Ticket price (USD)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label>:null}</fieldset>{notice?<div className="vc-ph06-alert">{notice}</div>:null}<div className="vc-ph06-form-actions"><button type="button" className="vc-button vc-button--secondary" onClick={()=>navigate(`/rooms/${roomId}`)}>Public Room View</button><button className="vc-button vc-button--primary" disabled={save.isPending}><Save/>{save.isPending?'Saving…':'Save Settings'}</button></div></form></section></div>}
