import { IsString, IsNotEmpty, IsOptional, IsEnum } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export enum ContentCategory {
  CHAT_MESSAGE = 'chat_message',
  ROOM_TITLE = 'room_title',
  USER_BIO = 'user_bio',
  ANNOUNCEMENT = 'announcement',
}

export class AnalyzeContentDto {
  @ApiProperty({
    description: 'Text content to analyze for safety and moderation compliance',
    example: 'Hey everyone welcome to the voice room!',
  })
  @IsString()
  @IsNotEmpty()
  text: string;

  @ApiPropertyOptional({
    description: 'Content category context',
    enum: ContentCategory,
    default: ContentCategory.CHAT_MESSAGE,
  })
  @IsEnum(ContentCategory)
  @IsOptional()
  category?: ContentCategory = ContentCategory.CHAT_MESSAGE;

  @ApiPropertyOptional({
    description: 'Room ID where content was posted',
    example: 'room-uuid-123',
  })
  @IsString()
  @IsOptional()
  roomId?: string;
}

export class DeviceBanDto {
  @ApiProperty({
    description: 'Device fingerprint ID to ban',
    example: 'fp_a8f9c1e0293b4a5d',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    description: 'Reason for device ban',
    example: 'Repeated spam and abusive chat conduct',
  })
  @IsString()
  @IsNotEmpty()
  reason: string;

  @ApiPropertyOptional({
    description: 'Associated user ID',
    example: 'user-uuid-123',
  })
  @IsString()
  @IsOptional()
  userId?: string;
}

export class RegisterModerationDeviceDto {
  @ApiProperty({
    description: 'Unique device fingerprint generated by client app',
    example: 'fp_a8f9c1e0293b4a5d',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiPropertyOptional({
    description: 'Client platform (iOS, Android, Web)',
    example: 'iOS 17.4',
  })
  @IsString()
  @IsOptional()
  platform?: string;

  @ApiPropertyOptional({
    description: 'Client IP address',
    example: '192.168.1.1',
  })
  @IsString()
  @IsOptional()
  ipAddress?: string;
}

// Backward-compatible source export; the runtime class name stays unique for Swagger.
export { RegisterModerationDeviceDto as RegisterDeviceDto };
