export enum ReferralStatus {
  PENDING = 'PENDING',
  QUALIFIED = 'QUALIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  FRAUD_FLAGGED = 'FRAUD_FLAGGED',
}

export enum ActivationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum QualificationStatus {
  PENDING = 'PENDING',
  QUALIFIED = 'QUALIFIED',
  REJECTED = 'REJECTED',
}

export enum RewardStatus {
  UNCLAIMED = 'UNCLAIMED',
  GRANTED = 'GRANTED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
}

export enum FraudStatus {
  CLEAN = 'CLEAN',
  SUSPECTED = 'SUSPECTED',
  CONFIRMED = 'CONFIRMED',
}

export enum RewardType {
  COINS = 'COINS',
  DIAMONDS = 'DIAMONDS',
  BONUS_COINS = 'BONUS_COINS',
  XP = 'XP',
  VIP_TRIAL = 'VIP_TRIAL',
  STORE_ITEM = 'STORE_ITEM',
  PROFILE_FRAME = 'PROFILE_FRAME',
  CHAT_BUBBLE = 'CHAT_BUBBLE',
  ENTRANCE_EFFECT = 'ENTRANCE_EFFECT',
}

export enum RewardTrigger {
  REGISTRATION = 'REGISTRATION',
  FIRST_LOGIN = 'FIRST_LOGIN',
  PROFILE_COMPLETION = 'PROFILE_COMPLETION',
  FIRST_VOICE_ROOM_JOIN = 'FIRST_VOICE_ROOM_JOIN',
  FIRST_GIFT_PURCHASE = 'FIRST_GIFT_PURCHASE',
  FIRST_WALLET_PURCHASE = 'FIRST_WALLET_PURCHASE',
  VIP_PURCHASE = 'VIP_PURCHASE',
  MILESTONE_REFERRALS = 'MILESTONE_REFERRALS',
}

export enum BlacklistType {
  IP = 'IP',
  DEVICE = 'DEVICE',
  USER = 'USER',
}

export enum FraudAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  BLACKLIST = 'BLACKLIST',
  SUSPEND = 'SUSPEND',
  RESTORE = 'RESTORE',
}
