export enum SocketErrorCode {
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  NOT_ROOM_OWNER = 'NOT_ROOM_OWNER',
  NOT_MODERATOR = 'NOT_MODERATOR',
  ALREADY_IN_QUEUE = 'ALREADY_IN_QUEUE',
  NOT_IN_QUEUE = 'NOT_IN_QUEUE',
  INVALID_EMOJI = 'INVALID_EMOJI',
  USER_NOT_ON_STAGE = 'USER_NOT_ON_STAGE',
  ALREADY_ON_STAGE = 'ALREADY_ON_STAGE',
  ROOM_CLOSED = 'ROOM_CLOSED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NO_INVITATION_FOUND = 'NO_INVITATION_FOUND',
}
