import React, { useCallback, useEffect, useState } from 'react';
import {
  Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent,
  DialogTitle, FormControl, InputLabel, MenuItem, Select, Tab, Table, TableBody,
  TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Typography,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import RefreshIcon from '@mui/icons-material/Refresh';
import { adminService } from '../services/admin.service';
import { useNotificationsStore } from '../store/notifications.store';

type Campaign = { id:string; campaignName:string; startDate:string; endDate:string; isActive:boolean; currentTotalReferrals:number; globalLimits:number };
type FraudLog = { id:string; relationshipId?:string; referrerId?:string; referredUserId?:string; triggerReason:string; riskScore:number; status:string; ipAddress?:string; createdAt:string };
type BlacklistItem = { id:string; type:string; value:string; reason?:string; createdAt:string };

export const ReferralPage: React.FC = () => {
  const addToast = useNotificationsStore((s) => s.addToast);
  const [tab,setTab]=useState(0); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [fraudLogs,setFraudLogs]=useState<FraudLog[]>([]); const [blacklist,setBlacklist]=useState<BlacklistItem[]>([]); const [analytics,setAnalytics]=useState<any>(null);
  const [campaignOpen,setCampaignOpen]=useState(false); const [blacklistOpen,setBlacklistOpen]=useState(false); const [rewardOpen,setRewardOpen]=useState(false);
  const [campaign,setCampaign]=useState({campaignName:'',startDate:'',endDate:'',globalLimits:0}); const [blacklistForm,setBlacklistForm]=useState({type:'IP',value:'',reason:''}); const [reward,setReward]=useState({userId:'',rewardType:'COINS',amount:100,reason:'Admin referral reward'});
  const load=useCallback(async()=>{try{const [c,f,b,a]=await Promise.all([adminService.getReferralCampaigns({page:1,limit:100}),adminService.getReferralFraudLogs({page:1,limit:100}),adminService.getReferralBlacklist({page:1,limit:100}),adminService.getReferralAnalytics()]);setCampaigns(c.data||[]);setFraudLogs(f.data||[]);setBlacklist(b.data||[]);setAnalytics(a)}catch(e:any){addToast('error',e?.response?.data?.message||'Failed to load referral data')}},[addToast]);
  useEffect(()=>{void load()},[load]);
  const createCampaign=async()=>{try{await adminService.createReferralCampaign({...campaign,startDate:new Date(campaign.startDate).toISOString(),endDate:new Date(campaign.endDate).toISOString(),isActive:true});setCampaignOpen(false);setCampaign({campaignName:'',startDate:'',endDate:'',globalLimits:0});await load();addToast('success','Referral campaign created')}catch(e:any){addToast('error',e?.response?.data?.message||'Failed to create campaign')}};
  const toggleCampaign=async(r:Campaign)=>{try{await adminService.updateReferralCampaign(r.id,{isActive:!r.isActive});await load()}catch(e:any){addToast('error',e?.response?.data?.message||'Failed to update campaign')}};
  const fraudAction=async(r:FraudLog,action:'APPROVE'|'REJECT'|'BLACKLIST')=>{try{await adminService.executeReferralFraudAction({action,relationshipId:r.relationshipId,referrerId:r.referrerId,referredUserId:r.referredUserId,reason:`Admin ${action}`});await load();addToast('success',`Fraud action ${action} completed`)}catch(e:any){addToast('error',e?.response?.data?.message||'Fraud action failed')}};
  const addBlacklist=async()=>{try{await adminService.addReferralBlacklist(blacklistForm);setBlacklistOpen(false);setBlacklistForm({type:'IP',value:'',reason:''});await load();addToast('success','Blacklist item added')}catch(e:any){addToast('error',e?.response?.data?.message||'Failed to add blacklist item')}};
  const grantReward=async()=>{try{await adminService.grantReferralReward({...reward,amount:Number(reward.amount)});setRewardOpen(false);await load();addToast('success','Referral reward granted')}catch(e:any){addToast('error',e?.response?.data?.message||'Failed to grant reward')}};
  const overview=analytics?.overview||{}; const fraud=analytics?.fraudStatistics||{}; const rewards=analytics?.rewardDistribution||{};
  return <Box sx={{p:3}}><Box sx={{display:'flex',justifyContent:'space-between',mb:3,gap:2}}><Box><Typography variant="h4" fontWeight={800}>Referral & Invite System</Typography><Typography color="text.secondary">Live referral campaigns, anti-fraud controls and rewards from the backend.</Typography></Box><Box><Button startIcon={<RefreshIcon/>} onClick={()=>void load()}>Refresh</Button><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setCampaignOpen(true)}>New Campaign</Button></Box></Box>
  <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(4,1fr)'},gap:2,mb:3}}>{[['Total Referrals',overview.totalReferrals??0],['Qualified',overview.successfulReferrals??0],['Fraud Logs',fraud.totalFraudLogs??0],['Rewards',rewards.totalRewardsGranted??0]].map(([l,v])=><Card key={String(l)}><CardContent><Typography variant="caption">{l}</Typography><Typography variant="h4" fontWeight={800}>{v}</Typography></CardContent></Card>)}</Box>
  <Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{mb:2}}><Tab label="Campaigns"/><Tab label="Fraud Review"/><Tab label="Blacklist"/><Tab label="Analytics"/></Tabs>
  {tab===0&&<TableContainer><Table><TableHead><TableRow><TableCell>Campaign</TableCell><TableCell>Period</TableCell><TableCell>Referrals</TableCell><TableCell>Status</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{campaigns.map(r=><TableRow key={r.id}><TableCell>{r.campaignName}</TableCell><TableCell>{new Date(r.startDate).toLocaleDateString()} – {new Date(r.endDate).toLocaleDateString()}</TableCell><TableCell>{r.currentTotalReferrals}{r.globalLimits?` / ${r.globalLimits}`:''}</TableCell><TableCell><Chip size="small" label={r.isActive?'ACTIVE':'INACTIVE'} color={r.isActive?'success':'default'}/></TableCell><TableCell><Button size="small" onClick={()=>void toggleCampaign(r)}>{r.isActive?'Disable':'Enable'}</Button><Button size="small" color="error" onClick={async()=>{await adminService.deleteReferralCampaign(r.id);await load()}}>Delete</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>}
  {tab===1&&<TableContainer><Table><TableHead><TableRow><TableCell>Risk</TableCell><TableCell>Reason</TableCell><TableCell>Referrer</TableCell><TableCell>Status</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{fraudLogs.map(r=><TableRow key={r.id}><TableCell>{r.riskScore}</TableCell><TableCell>{r.triggerReason}</TableCell><TableCell>{r.referrerId||'—'}</TableCell><TableCell>{r.status}</TableCell><TableCell><Button size="small" onClick={()=>void fraudAction(r,'APPROVE')}>Approve</Button><Button size="small" onClick={()=>void fraudAction(r,'REJECT')}>Reject</Button><Button size="small" color="warning" onClick={()=>void fraudAction(r,'BLACKLIST')}>Blacklist</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>}
  {tab===2&&<><Button sx={{mb:2}} variant="contained" onClick={()=>setBlacklistOpen(true)}>Add Blacklist</Button><TableContainer><Table><TableHead><TableRow><TableCell>Type</TableCell><TableCell>Value</TableCell><TableCell>Reason</TableCell><TableCell>Action</TableCell></TableRow></TableHead><TableBody>{blacklist.map(r=><TableRow key={r.id}><TableCell>{r.type}</TableCell><TableCell>{r.value}</TableCell><TableCell>{r.reason||'—'}</TableCell><TableCell><Button color="error" size="small" onClick={async()=>{await adminService.removeReferralBlacklist(r.id);await load()}}>Remove</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></>}
  {tab===3&&<Box><Typography>Total referrals: {overview.totalReferrals??0}</Typography><Typography>Conversion: {overview.conversionRate??0}%</Typography><Typography>Confirmed fraud: {fraud.confirmedFraudCount??0}</Typography><Typography>Blacklisted: {fraud.blacklistedCount??0}</Typography><Typography>Coins granted: {rewards.totalCoinsGranted??0}</Typography><Typography>Diamonds granted: {rewards.totalDiamondsGranted??0}</Typography><Button sx={{mt:2}} variant="contained" onClick={()=>setRewardOpen(true)}>Grant Manual Reward</Button></Box>}
  <Dialog open={campaignOpen} onClose={()=>setCampaignOpen(false)} fullWidth><DialogTitle>New Referral Campaign</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px !important'}}><TextField label="Campaign name" value={campaign.campaignName} onChange={e=>setCampaign({...campaign,campaignName:e.target.value})}/><TextField type="datetime-local" label="Start" InputLabelProps={{shrink:true}} value={campaign.startDate} onChange={e=>setCampaign({...campaign,startDate:e.target.value})}/><TextField type="datetime-local" label="End" InputLabelProps={{shrink:true}} value={campaign.endDate} onChange={e=>setCampaign({...campaign,endDate:e.target.value})}/><TextField type="number" label="Global limit (0 = unlimited)" value={campaign.globalLimits} onChange={e=>setCampaign({...campaign,globalLimits:Number(e.target.value)})}/></DialogContent><DialogActions><Button onClick={()=>setCampaignOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void createCampaign()}>Create</Button></DialogActions></Dialog>
  <Dialog open={blacklistOpen} onClose={()=>setBlacklistOpen(false)} fullWidth><DialogTitle>Add Blacklist</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px !important'}}><FormControl><InputLabel>Type</InputLabel><Select label="Type" value={blacklistForm.type} onChange={e=>setBlacklistForm({...blacklistForm,type:String(e.target.value)})}>{['IP','DEVICE','USER'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField label="Value" value={blacklistForm.value} onChange={e=>setBlacklistForm({...blacklistForm,value:e.target.value})}/><TextField label="Reason" value={blacklistForm.reason} onChange={e=>setBlacklistForm({...blacklistForm,reason:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setBlacklistOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void addBlacklist()}>Add</Button></DialogActions></Dialog>
  <Dialog open={rewardOpen} onClose={()=>setRewardOpen(false)} fullWidth><DialogTitle>Grant Referral Reward</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px !important'}}><TextField label="User ID" value={reward.userId} onChange={e=>setReward({...reward,userId:e.target.value})}/><FormControl><InputLabel>Reward</InputLabel><Select label="Reward" value={reward.rewardType} onChange={e=>setReward({...reward,rewardType:String(e.target.value)})}>{['COINS','DIAMONDS','BONUS_COINS','XP','VIP_TRIAL','STORE_ITEM','PROFILE_FRAME','CHAT_BUBBLE','ENTRANCE_EFFECT'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField type="number" label="Amount" value={reward.amount} onChange={e=>setReward({...reward,amount:Number(e.target.value)})}/></DialogContent><DialogActions><Button onClick={()=>setRewardOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void grantReward()}>Grant</Button></DialogActions></Dialog>
  </Box>;
};
