import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Alert, Box, Button, Card, CardContent, Divider, Grid, Typography } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import { AdminCreatorPayout, economyAdminService } from '../services/economy.service';

const Row = ({ label, value }: { label: string; value: any }) => <Box sx={{ py: 1 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="body2" sx={{ fontWeight: 600, wordBreak: 'break-word', whiteSpace: 'pre-wrap' }}>{value === null || value === undefined || value === '' ? '—' : String(value)}</Typography></Box>;
export const WalletPayoutDetailPage: React.FC = () => {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [payout, setPayout] = useState<AdminCreatorPayout | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { economyAdminService.getCreatorPayout(id).then(setPayout).catch((e) => setError(e?.response?.data?.message || e?.message || 'Failed to load payout')); }, [id]);
  return <Box><Button startIcon={<ArrowBackIcon />} onClick={() => navigate('/wallet')} sx={{ mb: 2 }}>Back to Wallet</Button>{error && <Alert severity="error">{error}</Alert>}{payout && <><Typography variant="h4" sx={{ fontWeight: 800, mb: 3 }}>Creator Payout Details</Typography><Grid container spacing={3}><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">Payout</Typography><Divider sx={{ my: 1 }} /><Row label="Payout Request ID" value={payout.id} /><Row label="Creator" value={payout.creatorName || payout.creatorUsername} /><Row label="Creator User ID" value={payout.creatorId} /><Row label="Diamonds" value={payout.diamondAmount} /><Row label="Amount" value={`$${Number(payout.payoutAmount).toFixed(2)} USD`} /><Row label="Method" value={payout.payoutMethod} /><Row label="Status" value={payout.status} /></CardContent></Card></Grid><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">Review & Settlement</Typography><Divider sx={{ my: 1 }} /><Row label="Reviewer" value={payout.reviewerName} /><Row label="Reviewer ID" value={payout.reviewedBy} /><Row label="Reviewed At" value={payout.reviewedAt ? new Date(payout.reviewedAt).toLocaleString() : null} /><Row label="Settled At" value={payout.settledAt ? new Date(payout.settledAt).toLocaleString() : null} /><Row label="Rejection Reason" value={payout.rejectionReason} /><Row label="Created" value={new Date(payout.createdAt).toLocaleString()} /><Row label="Updated" value={payout.updatedAt ? new Date(payout.updatedAt).toLocaleString() : null} /></CardContent></Card></Grid><Grid size={12}><Card><CardContent><Typography variant="h6">Payout Account Details</Typography><Divider sx={{ my: 1 }} /><Row label="Account Details" value={payout.accountDetails ? JSON.stringify(payout.accountDetails, null, 2) : null} /></CardContent></Card></Grid></Grid></>}</Box>;
};
