import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Alert, Box, Button, Card, CardContent, Divider, Grid, Typography } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import { AdminWalletTransaction, economyAdminService } from '../services/economy.service';

const Row = ({ label, value }: { label: string; value: any }) => <Box sx={{ py: 1 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="body2" sx={{ fontWeight: 600, wordBreak: 'break-word' }}>{value === null || value === undefined || value === '' ? '—' : String(value)}</Typography></Box>;
export const WalletTransactionDetailPage: React.FC = () => {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [tx, setTx] = useState<AdminWalletTransaction | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { economyAdminService.getTransaction(id).then(setTx).catch((e) => setError(e?.response?.data?.message || e?.message || 'Failed to load transaction')); }, [id]);
  return <Box><Button startIcon={<ArrowBackIcon />} onClick={() => navigate('/wallet')} sx={{ mb: 2 }}>Back to Wallet</Button>{error && <Alert severity="error">{error}</Alert>}{tx && <><Typography variant="h4" sx={{ fontWeight: 800, mb: 3 }}>Transaction Details</Typography><Grid container spacing={3}><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">Transaction</Typography><Divider sx={{ my: 1 }} /><Row label="Transaction ID" value={tx.id} /><Row label="Type" value={tx.transactionType} /><Row label="Amount" value={`${tx.amount} ${tx.currency}`} /><Row label="Method" value={tx.method || tx.source || tx.referenceType} /><Row label="Status" value={tx.status} /><Row label="Created" value={new Date(tx.createdAt).toLocaleString()} /></CardContent></Card></Grid><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">User & Authority</Typography><Divider sx={{ my: 1 }} /><Row label="User Name" value={tx.userName || tx.username} /><Row label="User ID" value={tx.userId} /><Row label="Balance Type" value={tx.balanceType} /><Row label="Balance Before" value={tx.balanceBefore} /><Row label="Balance After" value={tx.balanceAfter} /><Row label="Operation Key" value={tx.operationKey} /><Row label="Operation Group" value={tx.operationGroupId} /></CardContent></Card></Grid><Grid size={12}><Card><CardContent><Typography variant="h6">References & Metadata</Typography><Divider sx={{ my: 1 }} /><Row label="Source" value={tx.source} /><Row label="Destination" value={tx.destination} /><Row label="Reference Type" value={tx.referenceType} /><Row label="Reference ID" value={tx.referenceId} /><Row label="Description" value={tx.description} /><Row label="Remarks" value={tx.remarks} /><Row label="Metadata" value={tx.metadata ? JSON.stringify(tx.metadata, null, 2) : null} /></CardContent></Card></Grid></Grid></>}</Box>;
};
