export enum UserRole {
  USER = 'USER',
  GUEST = 'GUEST',
  CREATOR = 'CREATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum ClubRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  MEMBER = 'MEMBER',
}

export enum ScheduledRoomStatus {
  SCHEDULED = 'SCHEDULED',
  LIVE = 'LIVE',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  POSTPONED = 'POSTPONED',
}

export enum TicketStatus {
  ACTIVE = 'ACTIVE',
  USED = 'USED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum VisibilityType {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
  CLUB_ONLY = 'CLUB_ONLY',
  LINK_ONLY = 'LINK_ONLY',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum RsvpStatus {
  NONE = 'NONE',
  GOING = 'GOING',
  INTERESTED = 'INTERESTED',
  DECLINED = 'DECLINED',
}

export enum WalletTransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
  GIFT_PURCHASE = 'GIFT_PURCHASE',
  GIFT_EARNINGS = 'GIFT_EARNINGS',
  CREATOR_EARNINGS = 'CREATOR_EARNINGS',
  AGENCY_EARNINGS = 'AGENCY_EARNINGS',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  PURCHASE = 'PURCHASE',
  GIFT_SENT = 'GIFT_SENT',
  GIFT_RECEIVED = 'GIFT_RECEIVED',
  SUBSCRIPTION = 'SUBSCRIPTION',
  TICKET_PURCHASE = 'TICKET_PURCHASE',
  CREATOR_PAYOUT = 'CREATOR_PAYOUT',
  DIAMOND_CONVERSION = 'DIAMOND_CONVERSION',
  BONUS = 'BONUS',
  TRANSFER = 'TRANSFER',
  REVENUE_SETTLEMENT = 'REVENUE_SETTLEMENT',
  HOST_EARNINGS = 'HOST_EARNINGS',
  HOST_SETTLEMENT_RESERVE = 'HOST_SETTLEMENT_RESERVE',
  HOST_SETTLEMENT = 'HOST_SETTLEMENT',
}

export enum WalletCurrency {
  COIN = 'COIN',
  DIAMOND = 'DIAMOND',
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  INR = 'INR',
}

export enum WalletTransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum WalletBalanceType {
  COIN = 'COIN',
  DIAMOND = 'DIAMOND',
  BONUS = 'BONUS',
  PROMOTIONAL = 'PROMOTIONAL',
  FROZEN = 'FROZEN',
  WITHDRAWABLE = 'WITHDRAWABLE',
}

export enum PaymentProviderType {
  GOOGLE_PLAY = 'GOOGLE_PLAY',
  APPLE_IAP = 'APPLE_IAP',
  STRIPE = 'STRIPE',
  RAZORPAY = 'RAZORPAY',
  PAYPAL = 'PAYPAL',
  MOCK = 'MOCK',
}

export enum PurchaseStatus {
  INITIATED = 'INITIATED',
  VALIDATING = 'VALIDATING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum RefundStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

export enum RefundType {
  FULL = 'FULL',
  PARTIAL = 'PARTIAL',
  ADMIN = 'ADMIN',
}

export enum CreatorSettlementStatus {
  PENDING = 'PENDING',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum CreatorPlanStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSED = 'PROCESSED',
}

export enum PayoutMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  PAYPAL = 'PAYPAL',
  STRIPE = 'STRIPE',
  CRYPTO = 'CRYPTO',
}
